### ISSUE TITLE
submission.py

### ISSUE THREAD

**Issue by MichaelYu781** [david9dragon9/AIR#2]
Hi, thanks for sharing your code generously! Can you offer me some suggestions on how to use the ```submission.py``` to generate the final files which can be submitted to the ```https://waymo.com/open/challenges/2021/motion-prediction/```

**Comment by david9dragon9** [comment]
Hi,

Once you have finished training the model, you can pass in the loaded model and evaluation dataset to the `eval_and_generate_submission` function to generate the submission (after filling in the metadata about the submission), and then write the submission to file using the `write_submission_to_file` function. If you would like to split the data into different parts and generate a submission for each one, and then merge the resulting submission files, you can use the `combine_submission_bins` function.

**Comment by MichaelYu781** [comment]
Thanks for your reply! I will take a try.
